import {
  MOST_LISTENED_PODCASTS,
  RECENT_HOSTS,
  PREVIOUS_GUESTS,
  GET_PODCAST_BY_ID,
  ALL_POSTS,
  STAFF_LIST,
  GET_CURRENT_USER
} from "@gql/requests/queries/AdminQueries";

import {
  ALL_PODCASTS,
  POPULAR_POSTS,
  GET_POST_BY_ID
} from "@gql/requests/queries/ClientQueries";

export {
  ALL_POSTS,
  STAFF_LIST,
  RECENT_HOSTS,
  ALL_PODCASTS,
  GET_CURRENT_USER,
  POPULAR_POSTS,
  GET_POST_BY_ID,
  PREVIOUS_GUESTS,
  GET_PODCAST_BY_ID,
  MOST_LISTENED_PODCASTS,
}
