import Head from 'next/head'
import { RiArrowRightUpLine } from "react-icons/ri";
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import Image from 'next/image';
import { MyImage } from '@components/common';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GeoTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={`relative p-10 md:p-20`}>
          <div className='bg-gray-900 z-[-10] absolute inset-x-0 top-0 bottom-40'/>
          <div className={`flex flex-col gap-5 md:flex-row`}>
            <div className={`flex-1 flex flex-col gap-5 pt-7 text-white`}>
              <h2 className={`font-extrabold sm:text-7xl text-5xl xl:text-8xl`}>
                The best podcast for geo <span className={`relative before:content-[''] before:bg-red-400 before:w-34 before:h-32`}>ethusiasts.</span></h2>
              <p
                className='text-lg sm:text-xl'>
                Discover the best and latest in the geo-tech community and from seasoned geo technologists</p>
              <Link
                className={`
                  flex items-center gap-1 bg-red-500 text-white text-lg
                  hover:bg-red-600 active:bg-red-600 transition-all hover:gap-2
                  p-2 px-5 rounded-3xl w-fit`}
                href="/podcasts">Browse podcasts <span className="flex items-center gap-1"><RiArrowRightUpLine /></span></Link>
            </div>
            <div className={`flex-1 flex items-center gap-3`}>
              <div>
                <MyImage
                  className={`rounded-t-full rounded-b-full overflow-hidden max-w-xs`}
                  width={2893}
                  height={4339}
                  src="/images/laughing-podcast-guy.jpg"
                  alt="a dark dude lauging on a podcast"
                />
              </div>
              <div className='flex flex-col gap-3'>
                <MyImage
                  className={`rounded-t-full rounded-b-full overflow-hidden max-w-xs`}
                  width={4000}
                  height={6000}
                  alt="a whithe guy on a podcast"
                  src="/images/white-guy-on-podcast.jpg"/>
                <MyImage 
                  className={`rounded-t-full rounded-b-full overflow-hidden max-w-xs`}
                  width={3632}
                  height={4540}
                  alt="dark dude talking to a mic"
                  src="/images/podcast-guy.jpg"
                  />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
