import Head from 'next/head'
import { getMostPopularPosts } from "@api/client";
import { BlogLanding, PodcastLanding } from '@components/landingPage'
import { Maybe, PostTypeConnection } from '@gql/codegen/graphql';

export default function Home(props: { posts: Maybe<PostTypeConnection>}) {
  console.log(props);
  return (
    <>
      <Head>
        <title>GeoTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <PodcastLanding />
        <BlogLanding />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const posts = await getMostPopularPosts();
  return {
    props: {
      posts: posts.posts
    }
  }
}
